import { buildGoogleAuthorizationUrl, exchangeGoogleCode, createOAuthState, verifyOAuthState, scopeStatus } from "./oauth.js";

const KEY = "google:oauth:tokens";
const enc = new TextEncoder(); const dec = new TextDecoder();
const b64 = b => btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const unb64 = s => Uint8Array.from(atob(String(s).replace(/-/g,"+").replace(/_/g,"/") + "===".slice((String(s).length+3)%4)), c=>c.charCodeAt(0));
async function key(env){ if(!env.OAUTH_TOKEN_ENCRYPTION_KEY) throw new Error("OAUTH_TOKEN_ENCRYPTION_KEY is required"); const raw=await crypto.subtle.digest("SHA-256",enc.encode(env.OAUTH_TOKEN_ENCRYPTION_KEY)); return crypto.subtle.importKey("raw",raw,{name:"AES-GCM"},false,["encrypt","decrypt"]); }
async function seal(env,value){ const iv=crypto.getRandomValues(new Uint8Array(12)); const ct=await crypto.subtle.encrypt({name:"AES-GCM",iv},await key(env),enc.encode(JSON.stringify(value))); return `${b64(iv)}.${b64(ct)}`; }
async function unseal(env,value){ const [iv,ct]=String(value).split("."); if(!iv||!ct) throw new Error("INVALID_TOKEN_STORE_VALUE"); const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(iv)},await key(env),unb64(ct)); return JSON.parse(dec.decode(plain)); }
const hasStore = env => Boolean(env.OAUTH_TOKEN_STORE);
export async function saveTokens(env,tokens){ if(!hasStore(env)) throw new Error("OAUTH_TOKEN_STORE_KV binding is required"); await env.OAUTH_TOKEN_STORE.put(KEY,await seal(env,tokens)); }
export async function loadTokens(env){ if(!hasStore(env)) throw new Error("OAUTH_TOKEN_STORE_KV binding is required"); const value=await env.OAUTH_TOKEN_STORE.get(KEY); return value?unseal(env,value):null; }
export async function clearTokens(env){ if(hasStore(env)) await env.OAUTH_TOKEN_STORE.delete(KEY); }
export async function refreshAccessToken(env,tokens){ const body=new URLSearchParams({client_id:env.GOOGLE_OAUTH_CLIENT_ID,client_secret:env.GOOGLE_OAUTH_CLIENT_SECRET,refresh_token:tokens.refresh_token,grant_type:"refresh_token"}); const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body}); const data=await r.json(); if(!r.ok||!data.access_token){const e=new Error("GOOGLE_TOKEN_REFRESH_FAILED");e.status=r.status;e.details=data.error_description||data.error;throw e;} const updated={...tokens,...data,refresh_token:tokens.refresh_token,expires_at:Date.now()+Number(data.expires_in||3600)*1000}; await saveTokens(env,updated); return updated.access_token; }
export async function getValidAccessToken(env,{forceRefresh=false}={}){ const tokens=await loadTokens(env); if(!tokens?.access_token) throw new Error("GOOGLE_AUTH_REQUIRED"); if(!forceRefresh && Number(tokens.expires_at||0)>Date.now()+60000) return tokens.access_token; if(!tokens.refresh_token) throw new Error("GOOGLE_REAUTH_REQUIRED"); return refreshAccessToken(env,tokens); }
export async function beginOAuth(env){ const state=await createOAuthState(env); return buildGoogleAuthorizationUrl(env,state); }
export async function completeOAuth(env,state,code){ if(!(await verifyOAuthState(env,state))) throw new Error("INVALID_OAUTH_STATE"); if(!code) throw new Error("OAUTH_CODE_REQUIRED"); const tokens=await exchangeGoogleCode(env,code); await saveTokens(env,{...tokens,expires_at:Date.now()+Number(tokens.expires_in||3600)*1000}); return {connected:true,scope:tokens.scope||"",services:scopeStatus(tokens.scope||"")}; }
export async function oauthStatus(env){ if(!hasStore(env)) return {connected:false,storage:"not_configured",services:scopeStatus("")}; const tokens=await loadTokens(env); if(!tokens) return {connected:false,storage:"ready",services:scopeStatus("")}; return {connected:true,storage:"ready",expiresAt:tokens.expires_at||null,services:scopeStatus(tokens.scope||"")}; }
